on: push

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        versions:
          - os: macos-latest
            goos: darwin
            goarch: arm64
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: windows-latest
            goos: windows
            goarch: amd64
    runs-on: ${{ matrix.versions.os }}
    name: ${{ matrix.versions.goos }}-${{ matrix.versions.goarch }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: GOOS=${{ matrix.versions.goos }} GOARCH=${{ matrix.versions.goarch }} go build
        shell: bash
      - run: mv teralang teralang-${{ github.ref_name }}-${{ matrix.versions.goos }}-${{ matrix.versions.goarch }}
        if: ${{ matrix.versions.os != 'windows-latest' }}
      - run: mv teralang.exe teralang-${{ github.ref_name }}-${{ matrix.versions.goos }}-${{ matrix.versions.goarch }}.exe
        shell: bash
        if: ${{ matrix.versions.os == 'windows-latest' }}
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.versions.os != 'windows-latest' }}
        with:
          name: teralang-${{ matrix.versions.goos }}-${{ matrix.versions.goarch }}
          path: teralang-${{ github.ref_name }}-${{ matrix.versions.goos }}-${{ matrix.versions.goarch }}
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.versions.os == 'windows-latest' }}
        with:
          name: teralang-${{ matrix.versions.goos }}-${{ matrix.versions.goarch }}
          path: teralang-${{ github.ref_name }}-${{ matrix.versions.goos }}-${{ matrix.versions.goarch }}.exe
