on:
  push:
    tags: ["*"]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            goos: darwin
            goarch: arm64
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: windows-latest
            goos: windows
            goarch: amd64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.goos }}-${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build
        shell: bash
      - run: mv teralang teralang-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
        if: ${{ matrix.os != 'windows-latest' }}
      - run: mv teralang.exe teralang-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.exe
        shell: bash
        if: ${{ matrix.os == 'windows-latest' }}
      - uses: softprops/action-gh-release@v2
        if: ${{ matrix.os != 'windows-latest' }}
        with:
          files: |
            teralang-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
      - uses: softprops/action-gh-release@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          files: |
            teralang-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.exe
